n:
  workflow_dispatch:  # Allow manually triggering rollback
    inputs:
      commit_hash:
        required: true
        description: Git commit hash/tag for rollback

jobs:
  rollback:
    name: Rollback Terraform
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the specified commit
    - name: Checkout repository at rollback commit
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.commit_hash }}

    # Step 2: Set up AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Install Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Terraform Init
    - name: Terraform Initialize
      run: terraform init

    # Step 5: Terraform Apply (Rollback)
    - name: Terraform Apply (Rollback)
      run: terraform apply -auto-approve
